spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/news_system
  properties:
    hibernate:
      search:
        backend:
          type: lucene
          directory.root: ./data/index
  feign:
    client:
      comments-service:
        name: comments-service
        url: "http://localhost:8082"
cache:
  capacity: 10
  type: LRU


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://news-db:5432/news_system
    username: postgres
    password: postgres
  data:
    redis:
      host: cache-redis
      port: 6379
  cache:
    type: redis
  feign:
    client:
      comments-service:
        name: comments-service
        url: "http://comments-service:8082"

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/news_system
    username: postgres
    password: postgres
  feign:
    client:
      comments-service:
        name: comments-service
        url: "http://localhost:8082"
